Repository OCA/account-invoice-reporting, pull requests merged in 2021-01, with the labels that each got.

#152 [13.0][MIG] account_invoice_production_lot: Migration to 13.0
  account_invoice_production_lot/README.rst
  account_invoice_production_lot/__init__.py
  account_invoice_production_lot/__manifest__.py
  account_invoice_production_lot/demo/sale.xml
  account_invoice_production_lot/i18n/account_invoice_production_lot.pot
  account_invoice_production_lot/i18n/ar.po
  account_invoice_production_lot/i18n/bs.po
  account_invoice_production_lot/i18n/ca.po
  account_invoice_production_lot/i18n/cs.po
  account_invoice_production_lot/i18n/de.po
  account_invoice_production_lot/i18n/en_GB.po
  account_invoice_production_lot/i18n/es.po
  account_invoice_production_lot/i18n/es_CR.po
  account_invoice_production_lot/i18n/es_EC.po
  account_invoice_production_lot/i18n/es_MX.po
  account_invoice_production_lot/i18n/et.po
  account_invoice_production_lot/i18n/fr.po
  account_invoice_production_lot/i18n/fr_CH.po
  account_invoice_production_lot/i18n/hr.po
  account_invoice_production_lot/i18n/hr_HR.po
  account_invoice_production_lot/i18n/hu.po
  account_invoice_production_lot/i18n/it.po
  account_invoice_production_lot/i18n/ja.po
  account_invoice_production_lot/i18n/lt.po
  account_invoice_production_lot/i18n/mk.po
  account_invoice_production_lot/i18n/mn.po
  account_invoice_production_lot/i18n/nb.po
  account_invoice_production_lot/i18n/nl.po
  account_invoice_production_lot/i18n/nl_BE.po
  account_invoice_production_lot/i18n/nl_NL.po
  account_invoice_production_lot/i18n/pt.po
  account_invoice_production_lot/i18n/pt_BR.po
  account_invoice_production_lot/i18n/pt_PT.po
  account_invoice_production_lot/i18n/ro.po
  account_invoice_production_lot/i18n/ru.po
  account_invoice_production_lot/i18n/sl.po
  account_invoice_production_lot/i18n/sv.po
  account_invoice_production_lot/i18n/tr.po
  account_invoice_production_lot/i18n/tr_TR.po
  account_invoice_production_lot/i18n/zh_CN.po
  account_invoice_production_lot/i18n/zh_TW.po
  account_invoice_production_lot/models/__init__.py
  account_invoice_production_lot/models/account_invoice.py
  account_invoice_production_lot/readme/CONFIGURE.rst
  account_invoice_production_lot/readme/CONTRIBUTORS.rst
  account_invoice_production_lot/readme/DESCRIPTION.rst
  account_invoice_production_lot/readme/USAGE.rst
  account_invoice_production_lot/report/report_invoice.xml
  account_invoice_production_lot/static/description/icon.png
  account_invoice_production_lot/static/description/index.html
  account_invoice_production_lot/tests/__init__.py
  account_invoice_production_lot/tests/test_invoice_production_lot.py
  account_invoice_production_lot/views/account_invoice_views.xml
  setup/account_invoice_production_lot/odoo/addons/account_invoice_production_lot
  setup/account_invoice_production_lot/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#166 [14.0][MIG] account_invoice_report_grouped_by_picking: Migration to 14.0
  account_invoice_report_grouped_by_picking/README.rst
  account_invoice_report_grouped_by_picking/__init__.py
  account_invoice_report_grouped_by_picking/__manifest__.py
  account_invoice_report_grouped_by_picking/i18n/account_invoice_report_grouped_by_picking.pot
  account_invoice_report_grouped_by_picking/i18n/es.po
  account_invoice_report_grouped_by_picking/i18n/pt.po
  account_invoice_report_grouped_by_picking/models/__init__.py
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking/readme/CONTRIBUTORS.rst
  account_invoice_report_grouped_by_picking/readme/DESCRIPTION.rst
  account_invoice_report_grouped_by_picking/readme/USAGE.rst
  account_invoice_report_grouped_by_picking/static/description/icon.png
  account_invoice_report_grouped_by_picking/static/description/index.html
  account_invoice_report_grouped_by_picking/tests/__init__.py
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
  account_invoice_report_grouped_by_picking/views/report_invoice.xml
  setup/account_invoice_report_grouped_by_picking/odoo/addons/account_invoice_report_grouped_by_picking
  setup/account_invoice_report_grouped_by_picking/setup.py
Labels: approved, bot is merging ⏳

#168 [14.0][FIX] account_invoice_report_grouped_by_picking: invoice line without product
  account_invoice_report_grouped_by_picking/models/account_move.py
Labels: approved, bot is merging ⏳

#169 [13.0][FIX] account_invoice_report_grouped_by_picking: invoice line without…
  account_invoice_report_grouped_by_picking/models/account_move.py
Labels: bot is merging ⏳
