Repository OCA/account-invoice-reporting, pull requests merged in 2022-10, with the labels that each got.

#221 [15.0][MIG] account_invoice_line_sale_line_position
  account_invoice_line_sale_line_position/README.rst
  account_invoice_line_sale_line_position/__init__.py
  account_invoice_line_sale_line_position/__manifest__.py
  account_invoice_line_sale_line_position/i18n/account_invoice_line_sale_line_position.pot
  account_invoice_line_sale_line_position/i18n/de.po
  account_invoice_line_sale_line_position/models/__init__.py
  account_invoice_line_sale_line_position/models/account_invoice.py
  account_invoice_line_sale_line_position/readme/CONTRIBUTORS.rst
  account_invoice_line_sale_line_position/readme/CREDITS.rst
  account_invoice_line_sale_line_position/readme/DESCRIPTION.rst
  account_invoice_line_sale_line_position/report/invoice_report.xml
  account_invoice_line_sale_line_position/static/description/icon.png
  account_invoice_line_sale_line_position/static/description/index.html
  account_invoice_line_sale_line_position/tests/__init__.py
  account_invoice_line_sale_line_position/tests/test_account_invoice_line_sale_line_position.py
  account_invoice_line_sale_line_position/views/account_move_views.xml
  setup/account_invoice_line_sale_line_position/odoo/addons/account_invoice_line_sale_line_position
  setup/account_invoice_line_sale_line_position/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#224 [14.0] [MIG] account_invoice_report_grouped_by_picking_sale_mrp: Migration to 14.0
  README.md
  account_invoice_report_grouped_by_picking/__manifest__.py
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking_sale_mrp/README.rst
  account_invoice_report_grouped_by_picking_sale_mrp/__init__.py
  account_invoice_report_grouped_by_picking_sale_mrp/__manifest__.py
  account_invoice_report_grouped_by_picking_sale_mrp/i18n/account_invoice_report_grouped_by_picking_sale_mrp.pot
  account_invoice_report_grouped_by_picking_sale_mrp/i18n/es.po
  account_invoice_report_grouped_by_picking_sale_mrp/models/__init__.py
  account_invoice_report_grouped_by_picking_sale_mrp/models/account_move.py
  account_invoice_report_grouped_by_picking_sale_mrp/readme/CONTRIBUTORS.rst
  account_invoice_report_grouped_by_picking_sale_mrp/readme/DESCRIPTION.rst
  account_invoice_report_grouped_by_picking_sale_mrp/readme/USAGE.rst
  account_invoice_report_grouped_by_picking_sale_mrp/static/description/icon.png
  account_invoice_report_grouped_by_picking_sale_mrp/static/description/index.html
  account_invoice_report_grouped_by_picking_sale_mrp/tests/__init__.py
  account_invoice_report_grouped_by_picking_sale_mrp/tests/test_report_grouped_sale_mrp.py
  setup/account_invoice_report_grouped_by_picking_sale_mrp/odoo/addons/account_invoice_report_grouped_by_picking_sale_mrp
  setup/account_invoice_report_grouped_by_picking_sale_mrp/setup.py
Labels: bot is merging ⏳, stale

#241 [13.0][FIX] account_invoice_report_grouped_by_picking: Duplicated invoice lines
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: approved, bot is merging ⏳

#243 [14.0][FIX] account_invoice_report_grouped_by_picking: Duplicated invoice lines
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: approved, bot is merging ⏳

#244 [15.0][MIG] account_invoice_report_payment_info: Migration to version 15.0
  account_invoice_report_payment_info/README.rst
  account_invoice_report_payment_info/__init__.py
  account_invoice_report_payment_info/__manifest__.py
  account_invoice_report_payment_info/data/payment_info_data.xml
  account_invoice_report_payment_info/i18n/account_invoice_report_payment_info.pot
  account_invoice_report_payment_info/i18n/es.po
  account_invoice_report_payment_info/models/__init__.py
  account_invoice_report_payment_info/models/account_invoice.py
  account_invoice_report_payment_info/readme/CONFIGURE.rst
  account_invoice_report_payment_info/readme/CONTRIBUTORS.rst
  account_invoice_report_payment_info/readme/DESCRIPTION.rst
  account_invoice_report_payment_info/readme/USAGE.rst
  account_invoice_report_payment_info/static/description/icon.png
  account_invoice_report_payment_info/static/description/index.html
  account_invoice_report_payment_info/views/report_invoice.xml
  setup/account_invoice_report_payment_info/odoo/addons/account_invoice_report_payment_info
  setup/account_invoice_report_payment_info/setup.py
Labels: approved, bot is merging ⏳
