Repository OCA/account-invoice-reporting, pull requests merged in 2022-11, with the labels that each got.

#157 [14.0] [MIG] partner_time_to_pay
  partner_time_to_pay/README.rst
  partner_time_to_pay/__init__.py
  partner_time_to_pay/__manifest__.py
  partner_time_to_pay/i18n/fr.po
  partner_time_to_pay/i18n/nl_NL.po
  partner_time_to_pay/i18n/partner_time_to_pay.pot
  partner_time_to_pay/i18n/pt.po
  partner_time_to_pay/models/__init__.py
  partner_time_to_pay/models/res_partner.py
  partner_time_to_pay/readme/CONTRIBUTORS.rst
  partner_time_to_pay/readme/CREDITS.rst
  partner_time_to_pay/readme/DESCRIPTION.rst
  partner_time_to_pay/readme/INSTALL.rst
  partner_time_to_pay/readme/ROADMAP.rst
  partner_time_to_pay/readme/USAGE.rst
  partner_time_to_pay/static/description/icon.png
  partner_time_to_pay/static/description/index.html
  partner_time_to_pay/tests/__init__.py
  partner_time_to_pay/tests/test_partner_time_to_pay.py
  partner_time_to_pay/views/res_partner.xml
  setup/partner_time_to_pay/odoo/addons/partner_time_to_pay
  setup/partner_time_to_pay/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#245 [13.0][FIX] account_invoice_report_grouped_by_picking: refund invoice report
  account_invoice_report_grouped_by_picking/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#249 [15.0] [MIG] partner_time_to_pay + improvements
  partner_time_to_pay/README.rst
  partner_time_to_pay/__init__.py
  partner_time_to_pay/__manifest__.py
  partner_time_to_pay/i18n/es.po
  partner_time_to_pay/i18n/fr.po
  partner_time_to_pay/i18n/nl_NL.po
  partner_time_to_pay/i18n/partner_time_to_pay.pot
  partner_time_to_pay/i18n/pt.po
  partner_time_to_pay/models/__init__.py
  partner_time_to_pay/models/account_move.py
  partner_time_to_pay/models/res_partner.py
  partner_time_to_pay/readme/CONTRIBUTORS.rst
  partner_time_to_pay/readme/CREDITS.rst
  partner_time_to_pay/readme/DESCRIPTION.rst
  partner_time_to_pay/readme/INSTALL.rst
  partner_time_to_pay/readme/ROADMAP.rst
  partner_time_to_pay/readme/USAGE.rst
  partner_time_to_pay/static/description/icon.png
  partner_time_to_pay/static/description/index.html
  partner_time_to_pay/tests/__init__.py
  partner_time_to_pay/tests/test_partner_time_to_pay.py
  partner_time_to_pay/views/account_move_view.xml
  partner_time_to_pay/views/res_partner_view.xml
  setup/partner_time_to_pay/odoo/addons/partner_time_to_pay
  setup/partner_time_to_pay/setup.py
Labels: needs review, migration, bot is merging ⏳

#252 [15.0] [FIX] partner_time_to_pay: Fix calculation of full reconciliation date and swap d2x fields
  partner_time_to_pay/i18n/es.po
  partner_time_to_pay/i18n/partner_time_to_pay.pot
  partner_time_to_pay/models/account_move.py
  partner_time_to_pay/models/res_partner.py
  partner_time_to_pay/tests/test_partner_time_to_pay.py
  partner_time_to_pay/views/res_partner_view.xml
Labels: bug, needs review, approved, bot is merging ⏳

#253 [FIX] [15.0] partner_time_to_pay: Duplicate declaration of d2x_ytd, d2x_life
  partner_time_to_pay/models/res_partner.py
Labels: needs review, bot is merging ⏳

#251 [15.0][MIG] account_reporting_volume: Migration to 15.0
  account_reporting_volume/README.rst
  account_reporting_volume/__init__.py
  account_reporting_volume/__manifest__.py
  account_reporting_volume/i18n/account_reporting_volume.pot
  account_reporting_volume/i18n/es.po
  account_reporting_volume/models/__init__.py
  account_reporting_volume/models/account_invoice_report.py
  account_reporting_volume/readme/CONTRIBUTORS.rst
  account_reporting_volume/readme/DESCRIPTION.rst
  account_reporting_volume/readme/USAGE.rst
  account_reporting_volume/static/description/icon.png
  account_reporting_volume/static/description/index.html
  setup/account_reporting_volume/odoo/addons/account_reporting_volume
  setup/account_reporting_volume/setup.py
Labels: approved, bot is merging ⏳

#254 [15.0][FIX] account_comment_template: Set models field in templates created from tests.
  account_comment_template/tests/test_account_move_report.py
Labels: bot is merging ⏳
