Repository OCA/account-invoice-reporting, pull requests merged in 2022-02, with the labels that each got.

#204 [14.0][FIX] account_invoice_report_due_list: refund invoices header
  account_invoice_report_due_list/views/report_invoice.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳, stale

#207 [14.0][FIX] account_invoice_report_grouped_by_picking: filter sections and notes
  account_invoice_report_grouped_by_picking/README.rst
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking/readme/ROADMAP.rst
  account_invoice_report_grouped_by_picking/static/description/index.html
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: bot is merging ⏳, stale

#213 [14.0][IMP] account_invoice_report_grouped_by_picking: No display repeated lines for refund invoices without no returned quantities
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: bot is merging ⏳

#186 [14.0][MIG] account_invoice_report_hide_line
  account_invoice_report_hide_line/README.rst
  account_invoice_report_hide_line/__init__.py
  account_invoice_report_hide_line/__manifest__.py
  account_invoice_report_hide_line/i18n/account_invoice_report_hide_line.pot
  account_invoice_report_hide_line/i18n/hr.po
  account_invoice_report_hide_line/models/__init__.py
  account_invoice_report_hide_line/models/account_invoice.py
  account_invoice_report_hide_line/readme/CONTRIBUTORS.rst
  account_invoice_report_hide_line/readme/CREDITS.rst
  account_invoice_report_hide_line/readme/DESCRIPTION.rst
  account_invoice_report_hide_line/readme/USAGE.rst
  account_invoice_report_hide_line/static/description/icon.png
  account_invoice_report_hide_line/static/description/index.html
  account_invoice_report_hide_line/tests/__init__.py
  account_invoice_report_hide_line/tests/test_account_invoice_report.py
  account_invoice_report_hide_line/views/account_move_view.xml
  account_invoice_report_hide_line/views/report_invoice.xml
  setup/account_invoice_report_hide_line/odoo/addons/account_invoice_report_hide_line
  setup/account_invoice_report_hide_line/setup.py
Labels: needs review, migration, bot is merging ⏳, stale
