Repository OCA/account-invoice-reporting, pull requests merged in 2023-10, with the labels that each got.

#290 [16.0] [MIG] partner_time_to_pay
  partner_time_to_pay/README.rst
  partner_time_to_pay/__init__.py
  partner_time_to_pay/__manifest__.py
  partner_time_to_pay/i18n/ca.po
  partner_time_to_pay/i18n/es.po
  partner_time_to_pay/i18n/fr.po
  partner_time_to_pay/i18n/nl_NL.po
  partner_time_to_pay/i18n/partner_time_to_pay.pot
  partner_time_to_pay/i18n/pt.po
  partner_time_to_pay/models/__init__.py
  partner_time_to_pay/models/account_move.py
  partner_time_to_pay/models/res_partner.py
  partner_time_to_pay/readme/CONTRIBUTORS.rst
  partner_time_to_pay/readme/CREDITS.rst
  partner_time_to_pay/readme/DESCRIPTION.rst
  partner_time_to_pay/readme/INSTALL.rst
  partner_time_to_pay/readme/ROADMAP.rst
  partner_time_to_pay/readme/USAGE.rst
  partner_time_to_pay/static/description/icon.png
  partner_time_to_pay/static/description/index.html
  partner_time_to_pay/tests/__init__.py
  partner_time_to_pay/tests/test_partner_time_to_pay.py
  partner_time_to_pay/views/account_move_view.xml
  partner_time_to_pay/views/res_partner_view.xml
  setup/partner_time_to_pay/odoo/addons/partner_time_to_pay
  setup/partner_time_to_pay/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#285 [16.0][MIG] account_invoice_line_report
  account_invoice_line_report/README.rst
  account_invoice_line_report/__init__.py
  account_invoice_line_report/__manifest__.py
  account_invoice_line_report/i18n/account_invoice_line_report.pot
  account_invoice_line_report/i18n/ar.po
  account_invoice_line_report/i18n/bs.po
  account_invoice_line_report/i18n/ca.po
  account_invoice_line_report/i18n/cs.po
  account_invoice_line_report/i18n/de.po
  account_invoice_line_report/i18n/en_GB.po
  account_invoice_line_report/i18n/es.po
  account_invoice_line_report/i18n/es_CR.po
  account_invoice_line_report/i18n/es_EC.po
  account_invoice_line_report/i18n/es_MX.po
  account_invoice_line_report/i18n/et.po
  account_invoice_line_report/i18n/fr.po
  account_invoice_line_report/i18n/fr_CH.po
  account_invoice_line_report/i18n/fr_FR.po
  account_invoice_line_report/i18n/hr.po
  account_invoice_line_report/i18n/hr_HR.po
  account_invoice_line_report/i18n/hu.po
  account_invoice_line_report/i18n/it.po
  account_invoice_line_report/i18n/ja.po
  account_invoice_line_report/i18n/lt.po
  account_invoice_line_report/i18n/mk.po
  account_invoice_line_report/i18n/mn.po
  account_invoice_line_report/i18n/nb.po
  account_invoice_line_report/i18n/nl.po
  account_invoice_line_report/i18n/nl_BE.po
  account_invoice_line_report/i18n/nl_NL.po
  account_invoice_line_report/i18n/pt.po
  account_invoice_line_report/i18n/pt_BR.po
  account_invoice_line_report/i18n/pt_PT.po
  account_invoice_line_report/i18n/ro.po
  account_invoice_line_report/i18n/ru.po
  account_invoice_line_report/i18n/sl.po
  account_invoice_line_report/i18n/sv.po
  account_invoice_line_report/i18n/tr.po
  account_invoice_line_report/i18n/tr_TR.po
  account_invoice_line_report/i18n/zh_CN.po
  account_invoice_line_report/i18n/zh_TW.po
  account_invoice_line_report/readme/CONTRIBUTORS.rst
  account_invoice_line_report/readme/DESCRIPTION.rst
  account_invoice_line_report/readme/USAGE.rst
  account_invoice_line_report/report/account_invoice_report_view.xml
  account_invoice_line_report/static/description/icon.png
  account_invoice_line_report/static/description/index.html
  setup/account_invoice_line_report/odoo/addons/account_invoice_line_report
  setup/account_invoice_line_report/setup.py
Labels: approved, bot is merging ⏳

#291 [15.0] [IMP] improve tests performance
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: bot is merging ⏳

#292 [IMP] account_invoice_report_grouped_by_picking: test performance improvement
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: bot is merging ⏳

#293 [16.0][FIX] account_invoice_report_payment_info: compute should be multi
  account_invoice_report_payment_info/models/account_invoice.py
Labels: needs review, approved, bot is merging ⏳
