Repository OCA/account-invoice-reporting, pull requests merged in 2023-02, with the labels that each got.

#226 [ADD][12.0] account_reporting_net_weight: new module
  account_reporting_net_weight/README.rst
  account_reporting_net_weight/__init__.py
  account_reporting_net_weight/__manifest__.py
  account_reporting_net_weight/i18n/account_reporting_net_weight.pot
  account_reporting_net_weight/i18n/ca.po
  account_reporting_net_weight/i18n/es.po
  account_reporting_net_weight/readme/CONFIGURE.rst
  account_reporting_net_weight/readme/CONTRIBUTORS.rst
  account_reporting_net_weight/readme/DESCRIPTION.rst
  account_reporting_net_weight/readme/USAGE.rst
  account_reporting_net_weight/reports/__init__.py
  account_reporting_net_weight/reports/account_invoice_report.py
  account_reporting_net_weight/static/description/icon.png
  account_reporting_net_weight/static/description/index.html
  oca_dependencies.txt
  setup/account_reporting_net_weight/odoo/addons/account_reporting_net_weight
  setup/account_reporting_net_weight/setup.py
Labels: bot is merging ⏳

#266 [16.0] run copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#250 [15.0][MIG] account_invoice_line_report: Migration to 15.0
  account_invoice_line_report/README.rst
  account_invoice_line_report/__init__.py
  account_invoice_line_report/__manifest__.py
  account_invoice_line_report/i18n/account_invoice_line_report.pot
  account_invoice_line_report/i18n/ar.po
  account_invoice_line_report/i18n/bs.po
  account_invoice_line_report/i18n/ca.po
  account_invoice_line_report/i18n/cs.po
  account_invoice_line_report/i18n/de.po
  account_invoice_line_report/i18n/en_GB.po
  account_invoice_line_report/i18n/es.po
  account_invoice_line_report/i18n/es_CR.po
  account_invoice_line_report/i18n/es_EC.po
  account_invoice_line_report/i18n/es_MX.po
  account_invoice_line_report/i18n/et.po
  account_invoice_line_report/i18n/fr.po
  account_invoice_line_report/i18n/fr_CH.po
  account_invoice_line_report/i18n/fr_FR.po
  account_invoice_line_report/i18n/hr.po
  account_invoice_line_report/i18n/hr_HR.po
  account_invoice_line_report/i18n/hu.po
  account_invoice_line_report/i18n/it.po
  account_invoice_line_report/i18n/ja.po
  account_invoice_line_report/i18n/lt.po
  account_invoice_line_report/i18n/mk.po
  account_invoice_line_report/i18n/mn.po
  account_invoice_line_report/i18n/nb.po
  account_invoice_line_report/i18n/nl.po
  account_invoice_line_report/i18n/nl_BE.po
  account_invoice_line_report/i18n/nl_NL.po
  account_invoice_line_report/i18n/pt.po
  account_invoice_line_report/i18n/pt_BR.po
  account_invoice_line_report/i18n/pt_PT.po
  account_invoice_line_report/i18n/ro.po
  account_invoice_line_report/i18n/ru.po
  account_invoice_line_report/i18n/sl.po
  account_invoice_line_report/i18n/sv.po
  account_invoice_line_report/i18n/tr.po
  account_invoice_line_report/i18n/tr_TR.po
  account_invoice_line_report/i18n/zh_CN.po
  account_invoice_line_report/i18n/zh_TW.po
  account_invoice_line_report/readme/CONTRIBUTORS.rst
  account_invoice_line_report/readme/DESCRIPTION.rst
  account_invoice_line_report/readme/USAGE.rst
  account_invoice_line_report/report/account_invoice_report_view.xml
  account_invoice_line_report/static/description/icon.png
  account_invoice_line_report/static/description/index.html
  setup/account_invoice_line_report/odoo/addons/account_invoice_line_report
  setup/account_invoice_line_report/setup.py
Labels: approved, bot is merging ⏳

#261 [15.0][MIG] account_invoice_production_lot: Migration to 15.0
  account_invoice_production_lot/README.rst
  account_invoice_production_lot/__init__.py
  account_invoice_production_lot/__manifest__.py
  account_invoice_production_lot/demo/sale.xml
  account_invoice_production_lot/i18n/account_invoice_production_lot.pot
  account_invoice_production_lot/i18n/ar.po
  account_invoice_production_lot/i18n/bs.po
  account_invoice_production_lot/i18n/ca.po
  account_invoice_production_lot/i18n/cs.po
  account_invoice_production_lot/i18n/de.po
  account_invoice_production_lot/i18n/en_GB.po
  account_invoice_production_lot/i18n/es.po
  account_invoice_production_lot/i18n/es_CR.po
  account_invoice_production_lot/i18n/es_EC.po
  account_invoice_production_lot/i18n/es_MX.po
  account_invoice_production_lot/i18n/et.po
  account_invoice_production_lot/i18n/fr.po
  account_invoice_production_lot/i18n/fr_CH.po
  account_invoice_production_lot/i18n/hr.po
  account_invoice_production_lot/i18n/hr_HR.po
  account_invoice_production_lot/i18n/hu.po
  account_invoice_production_lot/i18n/it.po
  account_invoice_production_lot/i18n/ja.po
  account_invoice_production_lot/i18n/lt.po
  account_invoice_production_lot/i18n/mk.po
  account_invoice_production_lot/i18n/mn.po
  account_invoice_production_lot/i18n/nb.po
  account_invoice_production_lot/i18n/nl.po
  account_invoice_production_lot/i18n/nl_BE.po
  account_invoice_production_lot/i18n/nl_NL.po
  account_invoice_production_lot/i18n/pt.po
  account_invoice_production_lot/i18n/pt_BR.po
  account_invoice_production_lot/i18n/pt_PT.po
  account_invoice_production_lot/i18n/ro.po
  account_invoice_production_lot/i18n/ru.po
  account_invoice_production_lot/i18n/sl.po
  account_invoice_production_lot/i18n/sv.po
  account_invoice_production_lot/i18n/tr.po
  account_invoice_production_lot/i18n/tr_TR.po
  account_invoice_production_lot/i18n/zh_CN.po
  account_invoice_production_lot/i18n/zh_TW.po
  account_invoice_production_lot/models/__init__.py
  account_invoice_production_lot/models/account_invoice.py
  account_invoice_production_lot/readme/CONFIGURE.rst
  account_invoice_production_lot/readme/CONTRIBUTORS.rst
  account_invoice_production_lot/readme/DESCRIPTION.rst
  account_invoice_production_lot/readme/USAGE.rst
  account_invoice_production_lot/report/report_invoice.xml
  account_invoice_production_lot/static/description/icon.png
  account_invoice_production_lot/static/description/index.html
  account_invoice_production_lot/tests/__init__.py
  account_invoice_production_lot/tests/test_invoice_production_lot.py
  account_invoice_production_lot/views/account_invoice_views.xml
  setup/account_invoice_production_lot/odoo/addons/account_invoice_production_lot
  setup/account_invoice_production_lot/setup.py
Labels: approved, ready to merge, bot is merging ⏳
