Repository OCA/account-invoice-reporting, pull requests merged in 2024-05, with the labels that each got.

#315 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: help wanted, needs review, bot is merging ⏳

#314 [16.0][FIX] account_invoice_report_grouped_by_picking: reports of credit notes without lines.
  account_invoice_report_grouped_by_picking/models/account_move.py
Labels: approved, bot is merging ⏳

#316 [17.0][FIX] account_invoice_report_grouped_by_picking: reports of credit notes without lines.
  account_invoice_report_grouped_by_picking/models/account_move.py
Labels: approved, bot is merging ⏳

#311 [16.0][FIX] account_invoice_report_grouped_by_picking: Show lines/section in manually created invoice lines
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
  account_invoice_report_grouped_by_picking/views/report_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#318 [15.0][FIX] account_invoice_report_grouped_by_picking: Avoid crash on empty groups
  account_invoice_report_grouped_by_picking/views/report_invoice.xml
Labels: approved, bot is merging ⏳

#320 [FIX] [16.0] account_invoice_report_grouped_by_picking: next_line empty to avoid dict.get
  account_invoice_report_grouped_by_picking/README.rst
  account_invoice_report_grouped_by_picking/readme/CONTRIBUTORS.rst
  account_invoice_report_grouped_by_picking/static/description/index.html
  account_invoice_report_grouped_by_picking/views/report_invoice.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#323 [16.0][ADD] account_invoice_report_header_repeater: New module to repeat the header in all pages of the invoice report
  account_invoice_report_header_repeater/README.rst
  account_invoice_report_header_repeater/__init__.py
  account_invoice_report_header_repeater/__manifest__.py
  account_invoice_report_header_repeater/i18n/account_invoice_report_header_repeater.pot
  account_invoice_report_header_repeater/readme/CONTRIBUTORS.rst
  account_invoice_report_header_repeater/readme/DESCRIPTION.rst
  account_invoice_report_header_repeater/static/description/index.html
  account_invoice_report_header_repeater/views/report_invoice.xml
  setup/account_invoice_report_header_repeater/odoo/addons/account_invoice_report_header_repeater
  setup/account_invoice_report_header_repeater/setup.py
Labels: approved, bot is merging ⏳

#322 [ADD] [16.0] account_invoice_report_salesperson
  account_invoice_report_salesperson/README.rst
  account_invoice_report_salesperson/__init__.py
  account_invoice_report_salesperson/__manifest__.py
  account_invoice_report_salesperson/i18n/account_invoice_report_salesperson.pot
  account_invoice_report_salesperson/i18n/es.po
  account_invoice_report_salesperson/readme/CONTRIBUTORS.md
  account_invoice_report_salesperson/readme/DESCRIPTION.md
  account_invoice_report_salesperson/readme/USAGE.md
  account_invoice_report_salesperson/static/description/icon.png
  account_invoice_report_salesperson/static/description/index.html
  account_invoice_report_salesperson/views/report_invoice.xml
  setup/account_invoice_report_salesperson/odoo/addons/account_invoice_report_salesperson
  setup/account_invoice_report_salesperson/setup.py
Labels: approved, bot is merging ⏳
