Repository OCA/account-invoice-reporting, pull requests merged in 2025-03, with the labels that each got.

#359 [18.0][MIG] account_invoice_report_grouped_by_picking: Migration to 18.0
  account_invoice_report_grouped_by_picking/README.rst
  account_invoice_report_grouped_by_picking/__init__.py
  account_invoice_report_grouped_by_picking/__manifest__.py
  account_invoice_report_grouped_by_picking/i18n/account_invoice_report_grouped_by_picking.pot
  account_invoice_report_grouped_by_picking/i18n/de.po
  account_invoice_report_grouped_by_picking/i18n/es.po
  account_invoice_report_grouped_by_picking/i18n/fr_FR.po
  account_invoice_report_grouped_by_picking/i18n/it.po
  account_invoice_report_grouped_by_picking/i18n/pt.po
  account_invoice_report_grouped_by_picking/models/__init__.py
  account_invoice_report_grouped_by_picking/models/account_move.py
  account_invoice_report_grouped_by_picking/pyproject.toml
  account_invoice_report_grouped_by_picking/readme/CONTRIBUTORS.md
  account_invoice_report_grouped_by_picking/readme/CREDITS.md
  account_invoice_report_grouped_by_picking/readme/DESCRIPTION.md
  account_invoice_report_grouped_by_picking/readme/USAGE.md
  account_invoice_report_grouped_by_picking/static/description/icon.png
  account_invoice_report_grouped_by_picking/static/description/index.html
  account_invoice_report_grouped_by_picking/tests/__init__.py
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
  account_invoice_report_grouped_by_picking/views/report_invoice.xml
Labels: approved, bot is merging ⏳

#340 [15.0][MIG] account invoice report utm: Migration to 15.0
  account_invoice_report_utm/README.rst
  account_invoice_report_utm/__init__.py
  account_invoice_report_utm/__manifest__.py
  account_invoice_report_utm/i18n/account_invoice_report_utm_campaign.pot
  account_invoice_report_utm/readme/CONTRIBUTORS.rst
  account_invoice_report_utm/readme/DESCRIPTION.rst
  account_invoice_report_utm/report/__init__.py
  account_invoice_report_utm/report/account_invoice_report.py
  account_invoice_report_utm/static/description/icon.png
  account_invoice_report_utm/static/description/index.html
  setup/account_invoice_report_utm/odoo/addons/account_invoice_report_utm
  setup/account_invoice_report_utm/setup.py
Labels: approved, bot is merging ⏳, stale

#362 [16.0][FIX] account_invoice_production_lot: Fallback to load CoA
  account_invoice_production_lot/tests/test_invoice_production_lot.py
Labels: bot is merging ⏳

#361 [18.0][MIG] account_invoice_report_payment_info: Migration to 18.0
  account_invoice_report_payment_info/README.rst
  account_invoice_report_payment_info/__init__.py
  account_invoice_report_payment_info/__manifest__.py
  account_invoice_report_payment_info/data/payment_info_data.xml
  account_invoice_report_payment_info/i18n/account_invoice_report_payment_info.pot
  account_invoice_report_payment_info/i18n/es.po
  account_invoice_report_payment_info/i18n/it.po
  account_invoice_report_payment_info/models/__init__.py
  account_invoice_report_payment_info/models/account_invoice.py
  account_invoice_report_payment_info/pyproject.toml
  account_invoice_report_payment_info/readme/CONFIGURE.md
  account_invoice_report_payment_info/readme/CONTRIBUTORS.md
  account_invoice_report_payment_info/readme/DESCRIPTION.md
  account_invoice_report_payment_info/readme/USAGE.md
  account_invoice_report_payment_info/static/description/icon.png
  account_invoice_report_payment_info/static/description/index.html
  account_invoice_report_payment_info/views/report_invoice.xml
Labels: approved, bot is merging ⏳

#358 [18.0][MIG] account_invoice_line_report
  account_invoice_line_report/README.rst
  account_invoice_line_report/__init__.py
  account_invoice_line_report/__manifest__.py
  account_invoice_line_report/i18n/account_invoice_line_report.pot
  account_invoice_line_report/i18n/ar.po
  account_invoice_line_report/i18n/bs.po
  account_invoice_line_report/i18n/ca.po
  account_invoice_line_report/i18n/cs.po
  account_invoice_line_report/i18n/de.po
  account_invoice_line_report/i18n/en_GB.po
  account_invoice_line_report/i18n/es.po
  account_invoice_line_report/i18n/es_CR.po
  account_invoice_line_report/i18n/es_EC.po
  account_invoice_line_report/i18n/es_MX.po
  account_invoice_line_report/i18n/et.po
  account_invoice_line_report/i18n/fr.po
  account_invoice_line_report/i18n/fr_CH.po
  account_invoice_line_report/i18n/fr_FR.po
  account_invoice_line_report/i18n/hr.po
  account_invoice_line_report/i18n/hr_HR.po
  account_invoice_line_report/i18n/hu.po
  account_invoice_line_report/i18n/it.po
  account_invoice_line_report/i18n/ja.po
  account_invoice_line_report/i18n/lt.po
  account_invoice_line_report/i18n/mk.po
  account_invoice_line_report/i18n/mn.po
  account_invoice_line_report/i18n/nb.po
  account_invoice_line_report/i18n/nl.po
  account_invoice_line_report/i18n/nl_BE.po
  account_invoice_line_report/i18n/nl_NL.po
  account_invoice_line_report/i18n/pt.po
  account_invoice_line_report/i18n/pt_BR.po
  account_invoice_line_report/i18n/pt_PT.po
  account_invoice_line_report/i18n/ro.po
  account_invoice_line_report/i18n/ru.po
  account_invoice_line_report/i18n/sl.po
  account_invoice_line_report/i18n/sv.po
  account_invoice_line_report/i18n/tr.po
  account_invoice_line_report/i18n/tr_TR.po
  account_invoice_line_report/i18n/zh_CN.po
  account_invoice_line_report/i18n/zh_TW.po
  account_invoice_line_report/pyproject.toml
  account_invoice_line_report/readme/CONTRIBUTORS.md
  account_invoice_line_report/readme/DESCRIPTION.md
  account_invoice_line_report/readme/USAGE.md
  account_invoice_line_report/report/account_invoice_report_view.xml
  account_invoice_line_report/static/description/icon.png
  account_invoice_line_report/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳
