Repository OCA/account-invoice-reporting, pull requests merged in 2025-02, with the labels that each got.

#351 [ADD] [16.0] account_invoice_report_product_sticker
  account_invoice_report_product_sticker/README.rst
  account_invoice_report_product_sticker/__init__.py
  account_invoice_report_product_sticker/__manifest__.py
  account_invoice_report_product_sticker/i18n/account_invoice_report_product_sticker.pot
  account_invoice_report_product_sticker/i18n/es.po
  account_invoice_report_product_sticker/models/__init__.py
  account_invoice_report_product_sticker/models/account_move.py
  account_invoice_report_product_sticker/models/res_config_settings.py
  account_invoice_report_product_sticker/readme/CONTRIBUTORS.md
  account_invoice_report_product_sticker/readme/DESCRIPTION.md
  account_invoice_report_product_sticker/readme/INSTALL.md
  account_invoice_report_product_sticker/readme/USAGE.md
  account_invoice_report_product_sticker/static/description/icon.png
  account_invoice_report_product_sticker/static/description/index.html
  account_invoice_report_product_sticker/tests/__init__.py
  account_invoice_report_product_sticker/tests/common.py
  account_invoice_report_product_sticker/tests/test_account_move.py
  account_invoice_report_product_sticker/views/account_move_view.xml
  account_invoice_report_product_sticker/views/report_invoice.xml
  account_invoice_report_product_sticker/views/res_config_settings_view.xml
  setup/account_invoice_report_product_sticker/odoo/addons/account_invoice_report_product_sticker
  setup/account_invoice_report_product_sticker/setup.py
Labels: needs review, approved, bot is merging ⏳

#353 [FIX] [16.0] account_invoice_report_product_sticker: Select which model are being requesting stickers
  account_invoice_report_product_sticker/models/account_move.py
Labels: needs review, approved, bot is merging ⏳

#354 [16.0][FIX] account_invoice_report_due_list: Post-install test + fallback to load CoA
  account_invoice_report_due_list/tests/test_invoice_report_due_list.py
Labels: bot is merging ⏳

#355 [16.0][FIX] account_invoice_report_grouped_by_picking: Post-install test + fallback to load CoA
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: bot is merging ⏳

#343 [18.0][MIG] account_invoice_line_sale_line_position: Migration to 18.0
  account_invoice_line_sale_line_position/README.rst
  account_invoice_line_sale_line_position/__init__.py
  account_invoice_line_sale_line_position/__manifest__.py
  account_invoice_line_sale_line_position/i18n/account_invoice_line_sale_line_position.pot
  account_invoice_line_sale_line_position/i18n/de.po
  account_invoice_line_sale_line_position/i18n/es.po
  account_invoice_line_sale_line_position/models/__init__.py
  account_invoice_line_sale_line_position/models/account_invoice.py
  account_invoice_line_sale_line_position/pyproject.toml
  account_invoice_line_sale_line_position/readme/CONTRIBUTORS.md
  account_invoice_line_sale_line_position/readme/CREDITS.md
  account_invoice_line_sale_line_position/readme/DESCRIPTION.md
  account_invoice_line_sale_line_position/report/invoice_report.xml
  account_invoice_line_sale_line_position/static/description/icon.png
  account_invoice_line_sale_line_position/static/description/index.html
  account_invoice_line_sale_line_position/tests/__init__.py
  account_invoice_line_sale_line_position/tests/test_account_invoice_line_sale_line_position.py
  account_invoice_line_sale_line_position/views/account_move_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#357 [FIX] [16.0] account_invoice_report_product_sticker: Use product_sticker template
  account_invoice_report_product_sticker/views/report_invoice.xml
Labels: needs review, approved, bot is merging ⏳
